#name: ui-tests
#
#on:
#  push:
#    branches:
#      - main
#  pull_request:
#    branches:
#      - main
#  workflow_dispatch:
#
#
#jobs:
#  ui-test:
#    timeout-minutes: 30
#    runs-on: ubuntu-latest
#    env:
#      LOGIN: ${{ secrets.LOGIN }}
#      PASSWORD: ${{ secrets.PASSWORD }}
#    steps:
#      - uses: actions/checkout@v4
#      - name: Set up Python
#        uses: actions/setup-python@v4
#        with:
#          python-version: '3.11'
#      - name: Install dependencies
#        run: |
#          python -m pip install --upgrade pip
#          pip install -r ui_tests/requirements.txt
#      - name: Ensure browsers are installed
#        run: python -m playwright install --with-deps
#      - name: Run tests
#        run: pytest ui_tests -s
#      - uses: actions/upload-artifact@v4
#        if: ${{ !cancelled() }}
#        with:
#          name: allure_results
#          path: allure-results/
